### ISSUE TITLE
NewsManager类设计与实现

### ISSUE THREAD

**Issue by bennyguo** [bennyguo/AssemblyNews#4]
具体还没想好，是NewsManager和NewsGetter的衔接类，负责给NewsKeeper提供数据。
可能还需要设计一个数据库接口类。

**Comment by bennyguo** [comment]
需要提供的方法：

| 方法名 | 参数 | 返回类型 | 说明 |
| ------ | ----- | ----- | ------ |
| fetchLatest | ??? category, String keyword, int count | List\<NewsMeta\> | 获取相应类目中（含有某关键字的）count条最新新闻 |
| fetchAfter | NewsMeta nm, String keyword, int count | List\<NewsMeta\> | 获取某条新闻之后（含有某关键字的）count条新闻 |
| fetchContent | NewsMeta nm | News | 获取某条新闻的详细内容 |
| addToLikes | NewsMeta nm | boolean | 将某条新闻加入收藏夹 |
| removeFromLikes | NewsMeta nm | boolean | 将某条新闻从收藏夹删除 |

**Comment by bennyguo** [comment]
该类提供新闻的逻辑：
需要的内容是否在缓存中？
--是--> 从缓存中读取
--不在或不全在--> 从NewsGetter中获取，并放入缓存中

该类关于收藏夹的逻辑：
加入收藏夹：缓存其对应的Content
移除收藏夹：删除缓存中对应的Content

**Comment by wuqiling97** [comment]
现在还差无网络时读取本地的新闻列表没有实现了

**Comment by bennyguo** [comment]
fetchNewsMeta增加一个offLine参数，如果是false则返回离线缓存中的内容
