### ISSUE TITLE
TTS语音

### ISSUE THREAD

**Issue by bennyguo** [bennyguo/AssemblyNews#9]
将具体情况回复在下方

**Comment by ydc123** [comment]
设置搜索tts→第一个文字转语音（TTS）输出→文字转语音（TTS）输出
里面可以选语音引擎，Pico TTS是没有中文的，如果自带了讯飞语音+就非常好（声音自然有感情），如果有其他的或许也行。如果只有Pico TTS的话去下载一个讯飞语音+，然后选用这个就行了。
